TRUNCATE customer RESTART IDENTITY CASCADE;
TRUNCATE firm RESTART IDENTITY CASCADE;
TRUNCATE positions RESTART IDENTITY CASCADE;
TRUNCATE product RESTART IDENTITY CASCADE;
TRUNCATE stock RESTART IDENTITY CASCADE;
TRUNCATE stock_personal RESTART IDENTITY CASCADE;
TRUNCATE wagon RESTART IDENTITY CASCADE;